.TH focal "1" "October 26, 2011"
.SH NAME
focal \- interpreter for FOCAL
.SH SYNOPSIS
.B focal
.RI [\fIfile\fP]
.br
.SH DESCRIPTION
This manual page briefly documents the
.B focal
command. To run
.B focal
interactively, run it with no arguments. Alternatively, you can
pass the name of a file to
.B focal
on the command line. This will start
.B focal
and execute the code in the file.
.PP
For information about the FOCAL programming language handbook, read the
README distributed with this package.
.SH AUTHOR
.B focal
was written by Dave Pitts <dpitts@cozx.com>.
