CPU = i386
MAKECPU = /D_X86_
PCPU = /G3

!include <ntwin32.mak> 

EXE = .exe
OBJ = .obj
LIBEXT = .lib

RM = del
CP = copy

EXELIBS = /nologo /SUBSYSTEM:console $(LDEBUG) netapi32.lib wsock32.lib

CFLAGS = /nologo /DWIN32 /DANSICRT /DSTRERROR $(MAKECPU) $(DEBUG) /W3 /Zi /MD \
	$(PCPU) 

FOCALOBJS = focal$(OBJ) parser$(OBJ) screen$(OBJ)

all: focal$(EXE)

focal$(EXE) : $(FOCALOBJS) 
	link $(TARGET) $(FOCALOBJS) $(EXELIBS)

clean:
   $(RM) $(FOCALOBJS) focal$(EXE)

focal$(OBJ): focal.c parser.h errors.h perrors.h
parser$(OBJ): parser.c parser.h errors.h ptables.h stables.h psemant.h scanner.h
screen$(OBJ): screen.c
